import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarDemo from "@/components/NavbarDemo";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import { FloatingDockDemo } from "@/components/Floatdock";
import { AuthProvider } from "@/context/AuthContext"; // Import AuthProvider

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        {/* Wrap the entire app in AuthProvider */}
        <AuthProvider>
          <NavbarDemo />
          {children}
          <Footer />
          <FloatingDockDemo />
        </AuthProvider>

        {/* Toaster for notifications */}
        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
